apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-workflows-ml-demo

resources:
- ns.yaml
- artifact-repository.yaml
- minio-rbac.yaml
- minio-eventbinding.yaml
- wf-face-detect-rbac.yaml
- wf-face-detect.yaml
