apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: face-detect
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: key # s3 key in the face-detect bucket
      value: obama_and_biden.jpg

  serviceAccountName: face-detect

  # Optional. Indicates the artifact repository (s3 bucket) to use for intermediate artifacts for
  # the workflow (defined in the artifact-repositories ConfigMap). Uses the annotated default if omitted
  # artifactRepositoryRef:
  #   key: default

  # artifactGC:
  #   strategy: OnWorkflowDeletion
  #   serviceAccountName: face-detect

  templates:
    - name: main
      dag:
        tasks:
        - name: crop-faces
          template: crop-faces

        - name: iterate-faces
          dependencies: [crop-faces]
          template: iterate-faces

        - name: identify-face
          dependencies: [iterate-faces]
          withParam: "{{tasks.iterate-faces.outputs.result}}"
          template: identify-face
          arguments:
            artifacts:
            - name: face
              s3:
                key: "{{item}}"

        # To approve this workflow, set 
        # argo node set --node-field-selector displayName=approve -p approved="yes" face-detect-xxxxx
        # argo resume face-detect-xxxxx
        - name: approve
          dependencies: [identify-face]
          inline:
            suspend: {}
            outputs:
              parameters:
                - name: approved
                  valueFrom:
                    supplied: {}

        - name: fail
          dependencies: [approve]
          when: "'{{tasks.approve.outputs.parameters.approved}}' != 'yes'"
          inline:
            container:
              image: busybox:1.36
              command: [sh, -c]
              args: ["exit 1"]

        - name: finalize
          dependencies: [approve]
          when: "'{{tasks.approve.outputs.parameters.approved}}' == 'yes'"
          inline:
            container:
              image: busybox:1.36
              command: [sh, -c]
              args: ["echo success!"]

    # Downloads the image supplied to the workflow (workflow.parameters.key)
    # generates multiple cropped images of faces from the supplied image.
    - name: crop-faces
      inputs:
        artifacts:
        - name: images
          path: /tmp/input/{{workflow.parameters.key}}
          s3:
            insecure: true
            endpoint: minio.minio.svc:9000
            bucket: face-detect
            key: "{{workflow.parameters.key}}"
            accessKeySecret:
              name: minio
              key: username
            secretKeySecret:
              name: minio
              key: password
      script:
        image: hdgigante/python-opencv:4.7.0-ubuntu
        command: [/usr/bin/python3]
        source: |
          import cv2
          import os

          input_image = "/tmp/input/{{workflow.parameters.key}}"
          output_dir = "/tmp/cropped-faces/"
          os.mkdir(output_dir)

          # read the input image
          img = cv2.imread(input_image)

          # convert to grayscale of each frames
          gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

          # read the haarcascade to detect the faces in an image
          # face_cascade = cv2.CascadeClassifier('haarcascades\haarcascade_frontalface_default.xml')
          face_cascade = cv2.CascadeClassifier('/usr/local/share/opencv4/haarcascades/haarcascade_frontalface_default.xml')

          # detects faces in the input image
          faces = face_cascade.detectMultiScale(gray, 1.3, 4)
          print('Number of detected faces:', len(faces))

          # loop over all detected faces
          if len(faces) > 0:
            for i, (x, y, w, h) in enumerate(faces):
                # To draw a rectangle in a face
                cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 255), 2)
                face = img[y:y + h, x:x + w]
                #cv2.imshow("Cropped Face", face)
                cv2.imwrite(output_dir + f'face{i}.jpg', face)
                print(f"face{i}.jpg is saved")
      outputs:
        artifacts:
        - name: cropped-faces
          path: /tmp/cropped-faces
          archive:
            none: {}

    # Iterates the cropped faces that were generated by the `crop-faces` step, then 
    # produces a list of S3 key locations so that they can be identified in parallel
    - name: iterate-faces
      data:
        source:
          artifactPaths:
            name: workflow-artifacts
            s3:
              bucket: workflow-artifacts
              endpoint: minio.minio.svc:9000
              key: "{{workflow.name}}"
              insecure: true
              accessKeySecret:
                name: minio
                key: username
              secretKeySecret:
                name: minio
                key: password
        transformation:
          - expression: "filter(data, {# endsWith \".jpg\"})"
      outputs:
        # Workaround necessary for artifactPaths to work
        artifacts:
          - name: file
            path: /file

    # Accepts a face artifact + and an s3 bucket of known faces, then outputs the identity (name)
    # of the individual identified from the face
    - name: identify-face
      inputs:
        artifacts:
        - name: face
          path: /tmp/face
        - name: known-faces
          path: /data/known-faces
          s3:
            bucket: known-faces
            endpoint: minio.minio.svc:9000
            key: known-faces
            insecure: true
            accessKeySecret:
              name: minio
              key: username
            secretKeySecret:
              name: minio
              key: password
      container:
        image: iankoulski/face-recognition
        command: [sh, -c]
        args:
        - face_recognition /data/known-faces /tmp/face | cut -d, -f2 | tee /tmp/name
      outputs:
        parameters:
        - name: name
          valueFrom:
            path: /tmp/name
