# ServiceAccount & RBAC that the workflow will run as
apiVersion: v1
kind: ServiceAccount
metadata:
  name: face-detect

---  
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: face-detect
rules:
# pod get/watch is used to identify the container IDs of the current pod
# pod patch is used to annotate the step's outputs back to controller (e.g. artifact location)
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - patch
# logs get/watch are used to get the pods logs for script outputs, and for log archival
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
# RBAC necessary to delete workflow artifacts for GC
- apiGroups:
  - argoproj.io
  resources:
  - workflowartifactgctasks
  verbs:
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - workflowartifactgctasks/status
  verbs:
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: face-detect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: face-detect
subjects:
- kind: ServiceAccount
  name: face-detect
