apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio

resources:
- minio-ns.yaml
- minio-dep.yaml
- minio-svc.yaml
- minio-pvc.yaml

images:
- name: quay.io/minio/minio
  newTag: RELEASE.2023-08-09T23-30-22Z
